// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Caml_array = require("rescript/lib/js/caml_array.js");

var measurements = Fs.readFileSync("./src/Day01.txt", "utf8").split("\n").map(function (prim) {
      return Number(prim);
    });

function part1(param) {
  return measurements.reduce((function (acc, current, index) {
                var firstElement = index === 0;
                if (firstElement || measurements[index - 1 | 0] > current) {
                  return acc;
                } else {
                  return acc + 1 | 0;
                }
              }), 0);
}

function part2(param) {
  var getLargeMeasurement = function (measurements, _start) {
    while(true) {
      var start = _start;
      if ((start + 3 | 0) >= measurements.length) {
        return 0;
      }
      var first_sum = Caml_array.get(measurements, start) + Caml_array.get(measurements, start + 1 | 0) + Caml_array.get(measurements, start + 2 | 0);
      var second_sum = Caml_array.get(measurements, start + 1 | 0) + Caml_array.get(measurements, start + 2 | 0) + Caml_array.get(measurements, start + 3 | 0);
      if (first_sum < second_sum) {
        return 1 + getLargeMeasurement(measurements, start + 1 | 0) | 0;
      }
      _start = start + 1 | 0;
      continue ;
    };
  };
  return getLargeMeasurement(measurements, 0);
}

console.log(part1(undefined));

console.log(part2(undefined));

exports.measurements = measurements;
exports.part1 = part1;
exports.part2 = part2;
/* measurements Not a pure module */
