// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function getInputLines(file) {
  return Fs.readFileSync(file, "utf8").split("\n");
}

exports.getInputLines = getInputLines;
/* fs Not a pure module */
